/*
Autores:
  Aranda Marron Fernando 
  Chacon Jaral Hugo Emanuel
  Gutierrez Nolasco Emiliano 
Descripción: Script DDL para creación de la base de datos y estructura principal.
Fecha: 30/11/2025

Este script define la estructura completa de la base de datos 
de una aseguradora. Incluye la creación de tablas, llaves primarias 
y foráneas, restricciones de validación, así como la organización
final de los objetos dentro de esquemas lógicos. Su propósito es 
establecer una base sálida y coherente para el manejo de clientes, 
pólizas, seguros, corredores, pagos y siniestros dentro del sistema.

*/


CREATE DATABASE ASEGURADORA06;  
GO
USE ASEGURADORA06;
GO

/*--------------------------------------------------
  ORGANIZACIÓN EN ESQUEMAS
--------------------------------------------------*/
CREATE SCHEMA Personas;
GO
CREATE SCHEMA Seguros;
GO
CREATE SCHEMA Operaciones;
GO

/* CLIENTES Y SU INFORMACIÓN PERSONAL */
CREATE TABLE Personas.CLIENTE (
    ID_CLIENTE       INT NOT NULL PRIMARY KEY,
    RFC              VARCHAR(13) NULL,
    CURP             VARCHAR(18) NOT NULL,
    TIPO_CLIENTE     VARCHAR(10) NOT NULL,         
    NOMBRE           VARCHAR(70) NOT NULL,
    APELLIDO_P       VARCHAR(60) NOT NULL,
    APELLIDO_M       VARCHAR(60),
    FECHA_NACIMIENTO DATE NOT NULL,
    ID_CORREDOR	     INT NULL
);

CREATE TABLE Personas.CONTACTO (
    ID_CONTACTO   INT NOT NULL PRIMARY KEY,
    TIPO          VARCHAR(10) NOT NULL,
    VALOR         VARCHAR(150) NOT NULL,
    ID_CLIENTE    INT,
    FOREIGN KEY (ID_CLIENTE) REFERENCES Personas.CLIENTE(ID_CLIENTE)
);

CREATE TABLE Personas.DIRECCION (
    ID_CLIENTE   INT NOT NULL PRIMARY KEY,
    CALLE        VARCHAR(100) NOT NULL,
    NUMEXTERIOR  VARCHAR(20) NOT NULL,
    NUMINTERIOR  VARCHAR(20),
    COLONIA      VARCHAR(100) NOT NULL,
    FOREIGN KEY (ID_CLIENTE) REFERENCES Personas.CLIENTE(ID_CLIENTE)
);

CREATE TABLE Personas.DIRECCIONCP (
    ID_CPDIR    VARCHAR(40) NOT NULL PRIMARY KEY,
    ESTADO      VARCHAR(40) NOT NULL,
    CIUDAD      VARCHAR(40) NOT NULL,
    ID_CLIENTE  INT NOT NULL,
    FOREIGN KEY (ID_CLIENTE) REFERENCES Personas.CLIENTE(ID_CLIENTE)
);

/* INFORMACIÓN DE CORREDORES Y ASIGNACIÓN POR CÓDIGO POSTAL */
CREATE TABLE Personas.CORREDOR (
    ID_CORREDOR     INT NOT NULL PRIMARY KEY,
    APELLIDOMAT     VARCHAR(40),
    APELLIDOPAT     VARCHAR(40) NOT NULL,
    CEDULA_PROF     VARCHAR(30) NOT NULL,
    NUM_EMPLEADO    VARCHAR(30) NOT NULL,
    TIPO_EMPLEADO   VARCHAR(30) NOT NULL,
    FECHA_CONTRATACION DATE NOT NULL,
    NOMBRE          VARCHAR(40) NOT NULL,
    PORC_COMISION   DECIMAL(5,2) NOT NULL,
    ID_SUPERVISOR   INT
);

CREATE TABLE Personas.CP_CORREDOR (
    ID_CPCORREDOR  VARCHAR(10) NOT NULL PRIMARY KEY,
    CP_FINAL       VARCHAR(40) NOT NULL,
    CP_INICIAL     VARCHAR(40) NOT NULL,
    ID_CORREDOR    INT NOT NULL,
    FOREIGN KEY (ID_CORREDOR) REFERENCES Personas.CORREDOR(ID_CORREDOR)
);

/* COTIZACIONES Y REGISTRO DE CAMBIOS */
CREATE TABLE Operaciones.COTIZACION (
    NUM_COTIZACION      INT NOT NULL PRIMARY KEY,
    ID_CLIENTE          INT NOT NULL,
    FECHA_COTIZ         DATE NOT NULL,
    MONTO_EST_PRIMA     DECIMAL(14,2) NOT NULL,
    ESTADO              VARCHAR(40) NOT NULL,
    RECORDATORIO        VARCHAR(400),
    VIGENCIA_DIAS       VARCHAR(40) NOT NULL,
    FOREIGN KEY (ID_CLIENTE) REFERENCES Personas.CLIENTE(ID_CLIENTE)
);

CREATE TABLE Operaciones.BITACORA_COTIZACIONES (
    ID_BITACORA      INT NOT NULL PRIMARY KEY,
    NUM_COTIZACION   INT NOT NULL,
    FECHA_CAMBIO     DATE NOT NULL,
    NUEVO_ESTADO     VARCHAR(20) NOT NULL,
    OBSERVACIONES    VARCHAR(2000),
    FOREIGN KEY (NUM_COTIZACION) REFERENCES Operaciones.COTIZACION(NUM_COTIZACION)
);

/* TIPOS DE SEGURO Y ESPECIALIZACIONES */
CREATE TABLE Seguros.TIPO_SEGURO (
    CLAVE_SEGURO     VARCHAR(30) NOT NULL PRIMARY KEY,
    NOMBRE           VARCHAR(100) NOT NULL,
    DESCRIPCION      VARCHAR(4000),
    VIGENCIA_MIN_MES INT NOT NULL,
    MONTO_MINIMO     DECIMAL(14,2) NOT NULL,
    NUM_COTIZACION   INT NOT NULL,
    FOREIGN KEY (NUM_COTIZACION) REFERENCES Operaciones.COTIZACION(NUM_COTIZACION)
);

CREATE TABLE Seguros.SEGURO_VIDA (
    CLAVE_SEGURO      VARCHAR(30) NOT NULL PRIMARY KEY,
    CLAVE             VARCHAR(40) NOT NULL,
    EDAD_MAXIM_CONTR  INT NOT NULL,
    FOREIGN KEY (CLAVE_SEGURO) REFERENCES Seguros.TIPO_SEGURO(CLAVE_SEGURO)
);

CREATE TABLE Seguros.SEGURO_RETIRO (
    CLAVE_SEGURO      VARCHAR(30) NOT NULL PRIMARY KEY,
    EDAD_RETIRO       INT NOT NULL,
    APORTACION_MIN_MENSUAL DECIMAL(14,2) NOT NULL,
    FOREIGN KEY (CLAVE_SEGURO) REFERENCES Seguros.TIPO_SEGURO(CLAVE_SEGURO)
);

CREATE TABLE Seguros.SEGURO_AUTO (
    CLAVE_SEGURO      VARCHAR(30) NOT NULL PRIMARY KEY,
    COBERTURA_BASICA  VARCHAR(4000) NOT NULL,
    FOREIGN KEY (CLAVE_SEGURO) REFERENCES Seguros.TIPO_SEGURO(CLAVE_SEGURO)
);

/* VEHÍCULOS ASEGURADOS */
CREATE TABLE Seguros.VEHICULO (
    ID_VEHICULO      INT NOT NULL PRIMARY KEY,
    PLACAS           VARCHAR(20) NOT NULL,
    NUM_SERIE        VARCHAR(50) NOT NULL,
    MARCA            VARCHAR(60) NOT NULL,
    MODELO           VARCHAR(60) NOT NULL,
    ANIO             INT NOT NULL,
    VALOR_COMERCIAL  DECIMAL(14,2) NOT NULL,
    CLAVE_SEGURO     VARCHAR(30) NOT NULL,
    FOREIGN KEY (CLAVE_SEGURO) REFERENCES Seguros.TIPO_SEGURO(CLAVE_SEGURO)
);

/* BENEFICIARIOS DE PÓLIZAS */
CREATE TABLE Personas.BENEFICIARIO (
    ID_BENEFICIARIO INT NOT NULL PRIMARY KEY,
    APELLIDO_M      VARCHAR(40),
    APELLIDO_P      VARCHAR(40) NOT NULL,
    NOMBRE          VARCHAR(200) NOT NULL,
    PARENTESCO      VARCHAR(20) NOT NULL,
    PORCENTAJE      INT NOT NULL,
    CLAVE_SEGURO    VARCHAR(30) NOT NULL,
    ID_CLIENTE      INT NOT NULL,
    FOREIGN KEY (CLAVE_SEGURO) REFERENCES Seguros.TIPO_SEGURO(CLAVE_SEGURO),
    FOREIGN KEY (ID_CLIENTE) REFERENCES Personas.CLIENTE(ID_CLIENTE)
);

/* PÓLIZAS */
CREATE TABLE Operaciones.POLIZA (
    NUM_POLIZA       INT NOT NULL PRIMARY KEY,
    ID_CLIENTE       INT NOT NULL,
    ID_CORREDOR      INT NOT NULL,
    CLAVE_SEGURO     VARCHAR(30) NOT NULL,
    FECHA_INICIO     DATE NOT NULL,
    FECHA_FIN        DATE NOT NULL,
    SALDO_PENDIENTE  DECIMAL(14,2),
    MONTO_PRIMA_TOT  DECIMAL(14,2) NOT NULL,
    ESTADO_POLIZA    VARCHAR(20) NOT NULL,
    FOREIGN KEY (ID_CLIENTE) REFERENCES Personas.CLIENTE(ID_CLIENTE),
    FOREIGN KEY (ID_CORREDOR) REFERENCES Personas.CORREDOR(ID_CORREDOR),
    FOREIGN KEY (CLAVE_SEGURO) REFERENCES Seguros.TIPO_SEGURO(CLAVE_SEGURO)
);

/* PAGOS DE PÓLIZAS */
CREATE TABLE Operaciones.PAGO (
    ID_PAGO        INT NOT NULL PRIMARY KEY,
    NUM_POLIZA     INT NOT NULL,
    STSPAGO        VARCHAR(40) NOT NULL,
    NUM_PAGO       INT NOT NULL,
    FECHA_PAGO     DATE NOT NULL,
    MONTO_PAGADO   DECIMAL(14,2) NOT NULL,
    METODO_PAGO    VARCHAR(50) NOT NULL,
    FOREIGN KEY (NUM_POLIZA) REFERENCES Operaciones.POLIZA(NUM_POLIZA)
);

/* SINIESTROS Y AJUSTADORES */
CREATE TABLE Operaciones.SINIESTRO (
    NUM_SINIESTRO  INT NOT NULL PRIMARY KEY,
    NUM_POLIZA     INT NOT NULL,
    FECHA_HORA     DATETIME NOT NULL,
    LUGAR          VARCHAR(400) NOT NULL,
    CAUSA          VARCHAR(400) NOT NULL,
    MONTO_INDEMNIZ DECIMAL(14,2) NOT NULL,
    FECHA_REGISTRO DATE NOT NULL,
    FOREIGN KEY (NUM_POLIZA) REFERENCES Operaciones.POLIZA(NUM_POLIZA)
);

CREATE TABLE Personas.AJUSTADOR (
    ID_AJUSTADOR   INT NOT NULL PRIMARY KEY,
    NOMBRE         VARCHAR(200) NOT NULL,
    APELLIDO_M     VARCHAR(150),
    APELLIDO_P     VARCHAR(150) NOT NULL,
    NUM_SINIESTRO  INT,
    FOREIGN KEY (NUM_SINIESTRO) REFERENCES Operaciones.SINIESTRO(NUM_SINIESTRO)
);

/*--------------------------------------------------
  RESTRICCIONES Y CHECKS
--------------------------------------------------*/
ALTER TABLE Personas.CLIENTE ADD CONSTRAINT FK_CLIENTE_CORREDOR
    FOREIGN KEY (ID_CORREDOR) REFERENCES Personas.CORREDOR(ID_CORREDOR);

ALTER TABLE Personas.CORREDOR ADD CONSTRAINT FK_CORREDOR_SUPERVISOR
    FOREIGN KEY (ID_SUPERVISOR) REFERENCES Personas.CORREDOR(ID_CORREDOR);

ALTER TABLE Operaciones.POLIZA ADD CONSTRAINT CHK_POLIZA_PRIMA_POSITIVA
    CHECK (MONTO_PRIMA_TOT > 0);

ALTER TABLE Operaciones.POLIZA ADD CONSTRAINT CHK_POLIZA_VIGENCIA_LOGICA
    CHECK (FECHA_FIN > FECHA_INICIO);

ALTER TABLE Personas.CORREDOR ADD CONSTRAINT UQ_CORREDOR_CEDULA_PROF
    UNIQUE (CEDULA_PROF);

ALTER TABLE Personas.CLIENTE ADD CONSTRAINT CHK_CLIENTE_TIPO_CLIENTE
    CHECK (TIPO_CLIENTE IN ('NATURAL', 'MORAL'));

ALTER TABLE Personas.CONTACTO ADD CONSTRAINT CHK_CONTACTO_TIPO
    CHECK (TIPO IN ('TELEFONO', 'CORREO'));

ALTER TABLE Seguros.TIPO_SEGURO ADD CONSTRAINT CHK_TIPO_SEGURO_CLAVE
    CHECK (CLAVE_SEGURO IN ('100', '200', '300'));

ALTER TABLE Seguros.SEGURO_RETIRO ADD CONSTRAINT CHK_SEGRETIRO_CLAVE
    CHECK (CLAVE_SEGURO = '200');

ALTER TABLE Seguros.SEGURO_AUTO ADD CONSTRAINT CHK_SEGAUTO_CLAVE
    CHECK (CLAVE_SEGURO = '300');

ALTER TABLE Seguros.SEGURO_VIDA ADD CONSTRAINT CHK_SEGVIDA_CLAVE
    CHECK (CLAVE_SEGURO = '100');

ALTER TABLE Operaciones.POLIZA ADD CONSTRAINT CHK_POLIZA_ESTADO
    CHECK (ESTADO_POLIZA IN ('ACTIVA', 'INACTIVA'));

ALTER TABLE Operaciones.PAGO ADD CONSTRAINT CHK_PAGO_STATUS
    CHECK (STSPAGO IN ('PAGADO', 'PENDIENTE'));

ALTER TABLE Personas.CLIENTE ADD CONSTRAINT CHK_CLIENTE_EDAD_MAX
    CHECK (FECHA_NACIMIENTO >= DATEADD(YEAR, -80, GETDATE()));

ALTER TABLE Personas.BENEFICIARIO ADD CONSTRAINT CHK_BENEF_PARENTESCO_LINEA_DIRECTA
    CHECK (PARENTESCO IN ('P','M','HO','HA','CO'));
