/* =====================================
  Autores:
  Aranda Marron Fernando 
  Chacon Jaral Hugo Emanuel
  Gutierrez Nolasco Emiliano 
Descripción:DCL Usuarios 
Fecha: 30/11/2025

Este script define los roles del sistema, 
asigna permisos específicos según las funciones 
de cada puesto y finalmente crea los usuarios
que formarán parte de la base de datos. 
Su objetivo es asegurar una correcta administración 
de privilegios y un control adecuado del acceso a la
información.

===================================== */
use ASEGURADORA06;
go


-- 1) CREAMOS LOS ROLES PARA EL TIPO DE EMPLEADO 

CREATE ROLE ADMINISTRADOR_SEGURO;
GO
CREATE ROLE GERENTE;
GO
CREATE ROLE JEFE_COMERCIAL;
GO
CREATE ROLE JEFE_AGENCIA;
GO
CREATE ROLE ASESOR_COMERCIAL;
GO


-- 2) OTORGANDO PERMISOS DE LECTURA (SELECT)


-- CLIENTES Y SUS DATOS
GRANT SELECT ON Personas.CLIENTE       TO ADMINISTRADOR_SEGURO, GERENTE, JEFE_COMERCIAL, JEFE_AGENCIA, ASESOR_COMERCIAL;
GO
GRANT SELECT ON Personas.DIRECCION     TO ADMINISTRADOR_SEGURO, GERENTE, JEFE_COMERCIAL, JEFE_AGENCIA, ASESOR_COMERCIAL;
GO
GRANT SELECT ON Personas.CONTACTO      TO ADMINISTRADOR_SEGURO, GERENTE, JEFE_COMERCIAL, JEFE_AGENCIA, ASESOR_COMERCIAL;
GO
GRANT SELECT ON Personas.BENEFICIARIO  TO ADMINISTRADOR_SEGURO, GERENTE, JEFE_COMERCIAL, JEFE_AGENCIA;
GO

-- EMPLEADOS / CORREDORES
GRANT SELECT ON Personas.CORREDOR      TO ADMINISTRADOR_SEGURO, GERENTE, JEFE_COMERCIAL, JEFE_AGENCIA;
GO
GRANT SELECT ON Personas.AJUSTADOR     TO ADMINISTRADOR_SEGURO, GERENTE, JEFE_AGENCIA;
GO
GRANT SELECT ON Personas.CP_CORREDOR        TO ADMINISTRADOR_SEGURO, GERENTE, JEFE_COMERCIAL, JEFE_AGENCIA;
GO

-- SEGUROS
GRANT SELECT ON Seguros.TIPO_SEGURO    TO ADMINISTRADOR_SEGURO, GERENTE, JEFE_COMERCIAL, ASESOR_COMERCIAL;
GO
GRANT SELECT ON Seguros.SEGURO_AUTO    TO ADMINISTRADOR_SEGURO, GERENTE, JEFE_COMERCIAL, ASESOR_COMERCIAL;
GO
GRANT SELECT ON Seguros.SEGURO_VIDA    TO ADMINISTRADOR_SEGURO, GERENTE, JEFE_COMERCIAL, ASESOR_COMERCIAL;
GO
GRANT SELECT ON Seguros.SEGURO_RETIRO  TO ADMINISTRADOR_SEGURO, GERENTE, JEFE_COMERCIAL, ASESOR_COMERCIAL;
GO

-- POLIZAS / PAGOS / SINIESTROS / VEHICULOS
GRANT SELECT ON Seguros.VEHICULO           TO ADMINISTRADOR_SEGURO, GERENTE, JEFE_COMERCIAL, ASESOR_COMERCIAL;
GO
GRANT SELECT ON Operaciones.POLIZA         TO ADMINISTRADOR_SEGURO, GERENTE, JEFE_COMERCIAL, ASESOR_COMERCIAL;
GO
GRANT SELECT ON Operaciones.PAGO           TO ADMINISTRADOR_SEGURO, GERENTE, JEFE_COMERCIAL, ASESOR_COMERCIAL;
GO
GRANT SELECT ON Operaciones.SINIESTRO      TO ADMINISTRADOR_SEGURO, GERENTE, JEFE_COMERCIAL;
GO

-- COTIZACIONES Y BITÁCORA
GRANT SELECT ON Operaciones.COTIZACION             TO ADMINISTRADOR_SEGURO, GERENTE, JEFE_COMERCIAL, ASESOR_COMERCIAL;
GO
GRANT SELECT ON Operaciones.BITACORA_COTIZACIONES  TO ADMINISTRADOR_SEGURO, GERENTE, JEFE_COMERCIAL, ASESOR_COMERCIAL;
GO



-- 3) OTORGANDO PERMISOS DE INSERTAR (INSERT)


-- CLIENTES (administrados por ASESOR y ADMIN)
GRANT INSERT ON Personas.CLIENTE       TO ADMINISTRADOR_SEGURO, ASESOR_COMERCIAL;
GO
GRANT INSERT ON Personas.DIRECCION     TO ADMINISTRADOR_SEGURO, ASESOR_COMERCIAL;
GO
GRANT INSERT ON Personas.CONTACTO      TO ADMINISTRADOR_SEGURO, ASESOR_COMERCIAL;
GO
GRANT INSERT ON Personas.BENEFICIARIO  TO ADMINISTRADOR_SEGURO;
GO

-- EMPLEADOS / CORREDORES (solo ADMIN)
GRANT INSERT ON Personas.CORREDOR      TO ADMINISTRADOR_SEGURO;
GO
GRANT INSERT ON Personas.AJUSTADOR     TO ADMINISTRADOR_SEGURO;
GO
GRANT INSERT ON Personas.CP_CORREDOR        TO ADMINISTRADOR_SEGURO;
GO

-- SEGUROS (ADMIN y JEFE_COMERCIAL)
GRANT INSERT ON Seguros.TIPO_SEGURO    TO ADMINISTRADOR_SEGURO, JEFE_COMERCIAL;
GO
GRANT INSERT ON Seguros.SEGURO_AUTO    TO ADMINISTRADOR_SEGURO, JEFE_COMERCIAL;
GO
GRANT INSERT ON Seguros.SEGURO_VIDA    TO ADMINISTRADOR_SEGURO, JEFE_COMERCIAL;
GO
GRANT INSERT ON Seguros.SEGURO_RETIRO  TO ADMINISTRADOR_SEGURO, JEFE_COMERCIAL;
GO

-- POLIZAS / PAGOS / SINIESTROS / VEHICULOS
GRANT INSERT ON Seguros.VEHICULO           TO ADMINISTRADOR_SEGURO, JEFE_COMERCIAL;
GO
GRANT INSERT ON Operaciones.POLIZA         TO ADMINISTRADOR_SEGURO, ASESOR_COMERCIAL, JEFE_COMERCIAL;
GO
GRANT INSERT ON Operaciones.PAGO           TO ADMINISTRADOR_SEGURO, ASESOR_COMERCIAL;
GO
GRANT INSERT ON Operaciones.SINIESTRO      TO ADMINISTRADOR_SEGURO;
GO

-- COTIZACION / BITÁCORA (asesores y jefes)
GRANT INSERT ON Operaciones.COTIZACION             TO ADMINISTRADOR_SEGURO, ASESOR_COMERCIAL, JEFE_COMERCIAL;
GO
GRANT INSERT ON Operaciones.BITACORA_COTIZACIONES  TO ADMINISTRADOR_SEGURO, ASESOR_COMERCIAL, JEFE_COMERCIAL;
GO



-- 4) OTORGANDO PERMISOS DE ACTUALIZAR (UPDATE)


-- CLIENTES
GRANT UPDATE ON Personas.CLIENTE       TO ADMINISTRADOR_SEGURO, ASESOR_COMERCIAL;
GO
GRANT UPDATE ON Personas.DIRECCION     TO ADMINISTRADOR_SEGURO, ASESOR_COMERCIAL;
GO
GRANT UPDATE ON Personas.CONTACTO      TO ADMINISTRADOR_SEGURO, ASESOR_COMERCIAL;
GO
GRANT UPDATE ON Personas.BENEFICIARIO  TO ADMINISTRADOR_SEGURO;
GO

-- EMPLEADOS / CORREDORES
GRANT UPDATE ON Personas.CORREDOR      TO ADMINISTRADOR_SEGURO, JEFE_AGENCIA;
GO
GRANT UPDATE ON Personas.AJUSTADOR     TO ADMINISTRADOR_SEGURO;
GO
GRANT UPDATE ON Personas.CP_CORREDOR        TO ADMINISTRADOR_SEGURO;
GO

-- SEGUROS
GRANT UPDATE ON Seguros.TIPO_SEGURO    TO ADMINISTRADOR_SEGURO, JEFE_COMERCIAL;
GO
GRANT UPDATE ON Seguros.SEGURO_AUTO    TO ADMINISTRADOR_SEGURO, JEFE_COMERCIAL;
GO
GRANT UPDATE ON Seguros.SEGURO_VIDA    TO ADMINISTRADOR_SEGURO, JEFE_COMERCIAL;
GO
GRANT UPDATE ON Seguros.SEGURO_RETIRO  TO ADMINISTRADOR_SEGURO, JEFE_COMERCIAL;
GO

-- POLIZAS / PAGOS / SINIESTROS / VEHICULOS
GRANT UPDATE ON Seguros.VEHICULO           TO ADMINISTRADOR_SEGURO, JEFE_COMERCIAL;
GO
GRANT UPDATE ON Operaciones.POLIZA         TO ADMINISTRADOR_SEGURO, JEFE_COMERCIAL;
GO
GRANT UPDATE ON Operaciones.PAGO           TO ADMINISTRADOR_SEGURO;
GO
GRANT UPDATE ON Operaciones.SINIESTRO      TO ADMINISTRADOR_SEGURO;
GO

-- COTIZACIONES / BITÁCORA
GRANT UPDATE ON Operaciones.COTIZACION             TO ADMINISTRADOR_SEGURO, ASESOR_COMERCIAL, JEFE_COMERCIAL;
GO
GRANT UPDATE ON Operaciones.BITACORA_COTIZACIONES  TO ADMINISTRADOR_SEGURO, JEFE_COMERCIAL;
GO



-- 5) OTORGANDO PERMISOS DE BORRADO (DELETE)


GRANT DELETE ON Personas.CLIENTE       TO ADMINISTRADOR_SEGURO;
GO
GRANT DELETE ON Personas.DIRECCION     TO ADMINISTRADOR_SEGURO;
GO
GRANT DELETE ON Personas.CONTACTO      TO ADMINISTRADOR_SEGURO;
GO
GRANT DELETE ON Personas.BENEFICIARIO  TO ADMINISTRADOR_SEGURO;
GO

GRANT DELETE ON Personas.CORREDOR      TO ADMINISTRADOR_SEGURO;
GO
GRANT DELETE ON Personas.AJUSTADOR     TO ADMINISTRADOR_SEGURO;
GO
GRANT DELETE ON Personas.CP_CORREDOR        TO ADMINISTRADOR_SEGURO;
GO

GRANT DELETE ON Seguros.TIPO_SEGURO    TO ADMINISTRADOR_SEGURO;
GO
GRANT DELETE ON Seguros.SEGURO_AUTO    TO ADMINISTRADOR_SEGURO;
GO
GRANT DELETE ON Seguros.SEGURO_VIDA    TO ADMINISTRADOR_SEGURO;
GO
GRANT DELETE ON Seguros.SEGURO_RETIRO  TO ADMINISTRADOR_SEGURO;
GO

GRANT DELETE ON Seguros.VEHICULO           TO ADMINISTRADOR_SEGURO;
GO
GRANT DELETE ON Operaciones.POLIZA         TO ADMINISTRADOR_SEGURO;
GO
GRANT DELETE ON Operaciones.PAGO           TO ADMINISTRADOR_SEGURO;
GO
GRANT DELETE ON Operaciones.SINIESTRO      TO ADMINISTRADOR_SEGURO;
GO

GRANT DELETE ON Operaciones.COTIZACION             TO ADMINISTRADOR_SEGURO;
GO
GRANT DELETE ON Operaciones.BITACORA_COTIZACIONES  TO ADMINISTRADOR_SEGURO;
GO



-- 6) PERMISOS EXTRA PARA EL ADMINISTRADOR

GRANT ALTER ANY USER      TO ADMINISTRADOR_SEGURO;
GO
GRANT ALTER ANY ROLE      TO ADMINISTRADOR_SEGURO;
GO
GRANT CREATE PROCEDURE    TO ADMINISTRADOR_SEGURO;
GO
GRANT VIEW DEFINITION     TO ADMINISTRADOR_SEGURO;
GO



-- 7) CREACIÓN DE USUARIOS DE EJEMPLO (NOMBRES Y PASSWORDS CAMBIADOS)

-- Admin general de la ASEGURADORA06
CREATE LOGIN admin_seg WITH PASSWORD = N'AdminSeg#2025',
    DEFAULT_DATABASE = [ASEGURADORA06],
    CHECK_EXPIRATION = OFF;
GO
CREATE USER admin_seg FOR LOGIN admin_seg;
GO
ALTER ROLE ADMINISTRADOR_SEGURO ADD MEMBER admin_seg;
GO

-- Gerente
CREATE LOGIN gerente_seg WITH PASSWORD = N'GerenteSeg#2025',
    DEFAULT_DATABASE = [ASEGURADORA06],
    CHECK_EXPIRATION = OFF;
GO
CREATE USER gerente_seg FOR LOGIN gerente_seg;
GO
ALTER ROLE GERENTE ADD MEMBER gerente_seg;
GO

-- Jefe Comercial
CREATE LOGIN jefecom_seg WITH PASSWORD = N'JefeComSeg#2025',
    DEFAULT_DATABASE = [ASEGURADORA06],
    CHECK_EXPIRATION = OFF;
GO
CREATE USER jefecom_seg FOR LOGIN jefecom_seg;
GO
ALTER ROLE JEFE_COMERCIAL ADD MEMBER jefecom_seg;
GO

-- Asesor Comercial
CREATE LOGIN asesor_seg WITH PASSWORD = N'AsesorSeg#2025',
    DEFAULT_DATABASE = [ASEGURADORA06],
    CHECK_EXPIRATION = OFF;
GO
CREATE USER asesor_seg FOR LOGIN asesor_seg;
GO
ALTER ROLE ASESOR_COMERCIAL ADD MEMBER asesor_seg;
GO

-- Jefe de Agencia
CREATE LOGIN jefeag_seg WITH PASSWORD = N'JefeAgSeg#2025',
    DEFAULT_DATABASE = [ASEGURADORA06],
    CHECK_EXPIRATION = OFF;
GO
CREATE USER jefeag_seg FOR LOGIN jefeag_seg;
GO
ALTER ROLE JEFE_AGENCIA ADD MEMBER jefeag_seg;
GO


SELECT 
    r.name AS Rol,
    p.permission_name AS Permiso,
    p.state_desc AS Estado,
    OBJECT_NAME(p.major_id) AS Objeto
FROM sys.database_permissions p
JOIN sys.database_principals r ON p.grantee_principal_id = r.principal_id
WHERE r.name IN ('ADMINISTRADOR_SEGURO','GERENTE','JEFE_COMERCIAL','JEFE_AGENCIA','ASESOR_COMERCIAL')
ORDER BY r.name, Objeto;